import { useEffect, useState } from 'react';
import { Home, CalendarDays, Brain, Banknote, Footprints, Calendar, LogOut } from 'lucide-react';
import { AppProvider } from './store';
import { AuthProvider, useAuth } from './auth';
import { AuthScreen } from './AuthScreen';
import { Dashboard } from './src/screens/Dashboard';
import { AccountDetail } from './src/screens/AccountDetail';
import { Calendar as CalendarScreen } from './src/screens/Calendar';
import { Journey } from './src/screens/Journey';
import { Finances } from './src/screens/Finances';
import { Intelligence } from './src/screens/Intelligence';

type Tab = 'dashboard'|'calendario'|'jornada'|'financas'|'analise';
const TABS: {id:Tab;label:string;icon:typeof Home}[] = [{id:'dashboard',label:'Início',icon:Home},{id:'calendario',label:'Calendário',icon:CalendarDays},{id:'analise',label:'Inteligência',icon:Brain},{id:'financas',label:'Financeiro',icon:Banknote},{id:'jornada',label:'Jornada',icon:Footprints}];
function BottomNav({tab,setTab}:{tab:Tab;setTab:(tab:Tab)=>void}) { return <nav className="fixed bottom-0 left-1/2 -translate-x-1/2 z-40 w-full max-w-md border-t border-[#2A2A31] bg-[#0B0B0D]/95 backdrop-blur-xl px-2 pt-2 pb-[calc(8px+env(safe-area-inset-bottom))] md:hidden"><div className="grid grid-cols-5 gap-1">{TABS.map(({id,label,icon:Icon})=>{const active=tab===id;return <button key={id} onClick={()=>setTab(id)} className={`flex min-w-0 flex-col items-center justify-center gap-1 rounded-xl py-2 text-[10px] font-semibold ${active?'text-[#D4AF37] bg-[#17171C]':'text-gray-500'}`}><Icon size={19} strokeWidth={active?2.5:2}/><span className="truncate max-w-full">{label}</span></button>})}</div></nav>; }
function SideNav({tab,setTab}:{tab:Tab;setTab:(tab:Tab)=>void}) { return <aside className="hidden md:flex fixed left-0 top-0 bottom-0 w-64 flex-col border-r border-[#2A2A31] bg-[#0B0B0D] p-5 z-50"><div className="flex items-center gap-3 px-2 py-3 mb-8"><div className="w-10 h-10 rounded-full flex items-center justify-center bg-gradient-to-br from-[#D4AF37] to-[#a8862a]"><span className="text-black font-extrabold">P</span></div><div><b className="text-white">PROPCONTROL</b><div className="text-[9px] tracking-[.22em] text-[#D4AF37]">TRADING CONTROL</div></div></div><nav className="space-y-1">{TABS.map(({id,label,icon:Icon})=>{const active=tab===id;return <button key={id} onClick={()=>setTab(id)} className={`w-full flex items-center gap-3 px-4 py-3 rounded-xl text-sm font-semibold text-left ${active?'bg-[#17171C] text-[#D4AF37]':'text-gray-500 hover:bg-[#121216] hover:text-gray-200'}`}><Icon size={19}/>{label}</button>})}</nav><div className="mt-auto px-4 py-3 text-[11px] text-gray-600">PropControl · Gestão profissional</div></aside>; }
function GreetingBar(){const now=new Date();return <div className="flex items-center justify-between py-4"><div><h1 className="text-lg font-extrabold text-white">{now.getHours()<12?'Bom dia':now.getHours()<18?'Boa tarde':'Boa noite'}, Weslley! 👊</h1><p className="text-xs text-gray-500 mt-1">Foco total na execução. Um trade de cada vez.</p></div><div className="hidden sm:flex items-center gap-2 rounded-xl px-3 py-2 bg-[#17171C] border border-[#2A2A31]"><Calendar size={14} className="text-[#D4AF37]"/><span className="text-xs text-gray-400">{now.toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long',year:'numeric'})}</span></div></div>}
function AppContent(){const [tab,setTab]=useState<Tab>('dashboard');const [openAccountId,setOpenAccountId]=useState<string|null>(null);return <div className="min-h-screen bg-[#0B0B0D] text-gray-200"><SideNav tab={tab} setTab={setTab}/><div className="md:ml-64 min-h-screen"><header className="border-b border-[#2A2A31] bg-[#0B0B0D] px-5 md:px-8"><div className="max-w-7xl mx-auto"><div className="flex items-center justify-center py-3 md:hidden"><div className="flex items-center gap-2"><div className="w-8 h-8 rounded-full flex items-center justify-center bg-[#D4AF37]"><span className="text-black font-extrabold">P</span></div><b className="text-white">PROPCONTROL</b></div></div><div className="hidden md:block"><GreetingBar/></div></div></header><main className="px-4 md:px-8 pb-28 md:pb-10"><div className="max-w-7xl mx-auto">{openAccountId?<AccountDetail accountId={openAccountId} onBack={()=>setOpenAccountId(null)}/>:<>{tab==='dashboard'&&<Dashboard onOpenAccount={setOpenAccountId}/>} {tab==='calendario'&&<CalendarScreen/>} {tab==='analise'&&<Intelligence/>} {tab==='jornada'&&<Journey/>} {tab==='financas'&&<Finances/>}</>}</div></main><BottomNav tab={tab} setTab={setTab}/></div></div>}
function Root(){const {session,loading}=useAuth();useEffect(()=>{if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});},[]);if(loading)return <div className="min-h-screen flex items-center justify-center bg-[#0B0B0D] text-white">Carregando...</div>;if(!session)return <AuthScreen/>;return <AppProvider><AppContent/></AppProvider>}
export default function App(){return <AuthProvider><Root/></AuthProvider>}
