import { useEffect, useState } from 'react';
import { Home, CalendarDays, Brain, Banknote, Footprints, Calendar, X, Building2, Sun, Moon, Crown } from 'lucide-react';
import { AppProvider } from './store';
import { AuthProvider, useAuth } from './auth';
import { AuthScreen } from './AuthScreen';
import { Dashboard } from './src/screens/Dashboard';
import { AccountDetail } from './src/screens/AccountDetail';
import { Calendar as CalendarScreen } from './src/screens/Calendar';
import { Journey } from './src/screens/Journey';
import { Finances } from './src/screens/Finances';
import { Intelligence } from './src/screens/Intelligence';
import { RegisterTrade } from './src/screens/RegisterTrade';
import { ProprietaryFirms } from './src/screens/ProprietaryFirms';

type Tab = 'dashboard'|'calendario'|'mesas'|'jornada'|'financas'|'analise';
const TABS = [{id:'dashboard' as Tab,label:'Início',icon:Home},{id:'calendario' as Tab,label:'Calendário',icon:CalendarDays},{id:'mesas' as Tab,label:'Mesas',icon:Building2},{id:'analise' as Tab,label:'Inteligência',icon:Brain},{id:'financas' as Tab,label:'Financeiro',icon:Banknote},{id:'jornada' as Tab,label:'Jornada',icon:Footprints}];

const css=`.pc-shell{min-height:100vh;background:#0B0B0D;color:#eee}.pc-sidebar{display:none}.pc-content{min-height:100vh}.pc-header{height:70px;border-bottom:1px solid #24242B;background:#0B0B0D}.pc-header-inner{height:100%;display:flex;align-items:center;justify-content:space-between;padding:0 20px}.pc-main{max-width:1180px;margin:0 auto;padding:20px 16px 90px}.pc-mobile-nav{display:block}.pc-journey{width:100%}
/* Todas as telas internas usam o mesmo fundo estrutural do app. Os cards continuam com seus tons escuros próprios. */
.pc-account-detail > div:first-child,.pc-calendar,.pc-intelligence > div:first-child,.pc-journey > div:first-child,.pc-mesas > section:first-child{background:#0B0B0D!important}
@media(min-width:900px){.pc-sidebar{display:flex;position:fixed;inset:0 auto 0 0;width:220px;z-index:50;flex-direction:column;padding:24px 16px;background:#0E0E11;border-right:1px solid #24242B}.pc-content{margin-left:220px}.pc-header{height:68px}.pc-header-inner{padding:0 24px;max-width:none;margin:0}.pc-main{max-width:860px;margin:0;padding:24px 16px 50px}.pc-main>.pc-dashboard,.pc-main>.pc-calendar,.pc-main>.pc-journey,.pc-main>.pc-account-detail,.pc-main>.pc-intelligence,.pc-main>section,.pc-main>div:not(.pc-trade-modal){max-width:820px;margin-left:0;margin-right:0}.pc-dashboard{max-width:820px!important;margin:0!important}.pc-dashboard>div:first-child,.pc-dashboard>section{max-width:820px;margin-left:0;margin-right:0}
/* Desktop density: compact, left-aligned and intentionally leaves breathing room on wide screens. */
.pc-calendar{padding-top:8px!important;padding-left:0!important;padding-right:0!important}.pc-calendar>.mx-auto{max-width:820px!important;margin-left:0!important;margin-right:0!important}.pc-calendar section{padding:18px!important}.pc-calendar section:first-of-type{padding:18px!important}.pc-calendar .mb-6{margin-bottom:14px!important}.pc-calendar .grid.grid-cols-7{gap:5px!important}.pc-calendar .grid.grid-cols-7>button{border-radius:10px!important}.pc-calendar .pc-calendar-summary>div{min-height:76px!important;padding:10px!important}
.pc-journey{max-width:820px!important;margin:0!important}
.pc-mobile-nav{display:none}}
@media(min-width:900px) and (max-width:1200px){.pc-main{max-width:none;margin:0;padding-left:20px;padding-right:20px}.pc-sidebar{width:208px}.pc-content{margin-left:208px}.pc-main>.pc-dashboard,.pc-main>.pc-calendar,.pc-main>.pc-journey,.pc-main>.pc-account-detail,.pc-main>.pc-intelligence,.pc-main>section,.pc-main>div:not(.pc-trade-modal){max-width:820px}.pc-dashboard,.pc-calendar>.mx-auto{max-width:820px!important}}
.pc-trade-modal{position:fixed;inset:0;z-index:10000;display:grid;place-items:center;background:rgba(0,0,0,.72);backdrop-filter:blur(8px);padding:16px}.pc-trade-modal-card{position:relative;width:min(100%,672px);max-height:92vh;overflow:hidden;border:1px solid #4A3C16;border-radius:24px;background:#0A0A0D;box-shadow:0 28px 90px rgba(0,0,0,.75),0 0 40px rgba(212,175,55,.06)}.pc-trade-modal-scroll{height:100%;max-height:92vh;overflow-y:auto;overscroll-behavior:contain}.pc-trade-modal .register-trade{max-width:none!important;padding:0 16px 22px!important}.pc-trade-modal .register-trade>div:first-child{padding-top:16px!important}.pc-trade-modal .register-trade>div:first-child>button:first-child{visibility:hidden;width:40px}.pc-trade-modal .register-trade>div:first-child>div:last-child{visibility:hidden}.pc-trade-modal .register-trade>div:first-child h1{font-size:18px!important;text-transform:uppercase;letter-spacing:.08em}.pc-trade-modal .register-trade>div:first-child p{display:none}.pc-trade-modal .register-trade>section:first-of-type{margin-top:10px!important;padding:14px!important;border-radius:18px!important}.pc-trade-modal .register-trade>section:first-of-type>div{gap:12px!important}.pc-trade-modal .register-trade>section:first-of-type .h-24{width:48px!important;height:48px!important;border-radius:14px!important}.pc-trade-modal .register-trade>section:first-of-type .text-4xl{font-size:20px!important}.pc-trade-modal .register-trade>section:first-of-type h2{font-size:15px!important}.pc-trade-modal .register-trade>section:first-of-type .mt-4{margin-top:8px!important}.pc-trade-modal .register-trade>section:nth-of-type(2){margin-top:12px!important;padding:16px!important;border-radius:18px!important}.pc-trade-modal .register-trade>section:nth-of-type(2)>div:nth-of-type(2){grid-template-columns:1fr!important;gap:12px!important;margin-top:14px!important}.pc-trade-modal .register-trade>section:nth-of-type(2)>div:nth-of-type(5){grid-template-columns:repeat(3,minmax(0,1fr))!important}.pc-trade-modal .register-trade>section:nth-of-type(2) .h-16{height:52px!important}.pc-trade-modal .register-trade>section:nth-of-type(2) textarea{min-height:100px!important}.pc-trade-modal .register-trade>section:nth-of-type(2) .my-6{margin-top:14px!important;margin-bottom:14px!important}.pc-trade-modal .register-trade>button{height:58px!important;margin-top:12px!important;font-size:15px!important}.pc-trade-modal .register-trade>div:last-child{display:none}@media(max-width:520px){.pc-trade-modal{padding:8px}.pc-trade-modal-card{max-height:92vh;border-radius:20px}.pc-trade-modal-scroll{max-height:92vh}.pc-trade-modal .register-trade{padding-left:12px!important;padding-right:12px!important}.pc-trade-modal .register-trade>section:nth-of-type(2){padding:14px!important}}
`;
function NavItems({tab,setTab}:{tab:Tab;setTab:(tab:Tab)=>void}){return <nav style={{display:'grid',gap:4}}>{TABS.map(({id,label,icon:Icon})=>{const a=tab===id;return <button key={id} onClick={()=>setTab(id)} style={{display:'flex',alignItems:'center',gap:12,width:'100%',padding:'11px 13px',border:0,borderRadius:12,background:a?'#1A1A20':'transparent',color:a?'#D4AF37':'#777782',fontSize:13,fontWeight:700,textAlign:'left',cursor:'pointer'}}><Icon size={18}/>{label}</button>})}</nav>}
function Sidebar({tab,setTab}:{tab:Tab;setTab:(tab:Tab)=>void}){return <aside className="pc-sidebar"><div style={{display:'flex',alignItems:'center',gap:12,padding:'0 6px',marginBottom:30}}><div style={{width:40,height:40,borderRadius:'50%',display:'grid',placeItems:'center',background:'radial-gradient(circle at 30% 30%,#F2CB4E,#9E7D19)',boxShadow:'0 0 14px rgba(212,175,55,.35)',color:'#0A0A0A',fontWeight:900,fontSize:19,fontFamily:'Manrope,Inter,sans-serif'}}>P</div><div style={{lineHeight:1.1}}><div style={{fontSize:15,fontWeight:900,color:'#fff',letterSpacing:'.02em'}}>PROP CONTROL</div><div style={{fontSize:7,color:'#D4AF37',letterSpacing:'.22em',fontWeight:800,marginTop:3}}>SISTEMA OPERACIONAL TRADER</div></div></div><div style={{fontSize:9,color:'#55555F',fontWeight:800,letterSpacing:'.16em',padding:'0 13px 9px'}}>MENU PRINCIPAL</div><NavItems tab={tab} setTab={setTab}/><div style={{marginTop:'auto',padding:'16px 13px 4px',borderTop:'1px solid #1C1C22'}}><Crown size={18} color="#D4AF37"/><p style={{fontSize:11,color:'#8A8A93',fontStyle:'italic',fontWeight:600,margin:'8px 0 0',lineHeight:1.4}}>&ldquo;Disciplina hoje, liberdade amanh&atilde;.&rdquo;</p><div style={{fontSize:9,color:'#4A4A53',fontWeight:800,letterSpacing:'.24em',marginTop:12}}>PROP CONTROL</div></div></aside>}
function MobileNav({tab,setTab}:{tab:Tab;setTab:(tab:Tab)=>void}){return <nav className="pc-mobile-nav" style={{position:'fixed',bottom:0,left:0,right:0,zIndex:9999,height:74,background:'#0B0B0D',borderTop:'1px solid #292930'}}><div style={{maxWidth:620,height:74,margin:'0 auto',display:'grid',gridTemplateColumns:'repeat(6,1fr)',alignItems:'center'}}>{TABS.map(({id,label,icon:Icon})=>{const a=tab===id;return <button key={id} onClick={()=>setTab(id)} style={{height:62,border:0,background:'transparent',color:a?'#D4AF37':'#73737D',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',gap:5,fontSize:9,fontWeight:700}}><Icon size={19}/><span>{label}</span></button>})}</div></nav>}
function Header(){const now=new Date();const h=now.getHours();const period=h<12?'dia':h<18?'tarde':'noite';const isNight=h>=18||h<6;const GreetIcon=isNight?Moon:Sun;const date=now.toLocaleDateString('pt-BR',{day:'2-digit',month:'short',year:'numeric'}).replace('.','').replace(/de\s(\w)/,(_,c)=>'de '+c.toUpperCase());return <header className="pc-header"><div className="pc-header-inner"><div style={{display:'flex',alignItems:'center',gap:14}}><div style={{width:44,height:44,borderRadius:14,display:'grid',placeItems:'center',flexShrink:0,background:'radial-gradient(circle,#2A2000 0%,#141008 100%)',border:'1px solid rgba(212,175,55,.4)',boxShadow:'0 0 18px rgba(212,175,55,.15)'}}><GreetIcon size={22} color="#D4AF37" strokeWidth={2}/></div><div><div style={{fontSize:21,fontWeight:850,color:'#fff',letterSpacing:'-.01em'}}>Boa {period}, Weslley!</div><div style={{fontSize:12,color:'#7A7A85',marginTop:3,fontStyle:'italic',fontWeight:600}}>Disciplina hoje, liberdade amanhã.</div></div></div><div style={{display:'flex',alignItems:'center',gap:8,padding:'10px 14px',border:'1px solid #34343C',borderRadius:12,background:'#111116',color:'#B8B8C2',fontSize:12,fontWeight:600}}><Calendar size={14} color="#D4AF37"/>{date}</div></div></header>}
function AppContent(){const [tab,setTab]=useState<Tab>('dashboard');const [openAccountId,setOpenAccountId]=useState<string|null>(null);const [registerAccountId,setRegisterAccountId]=useState<string|null>(null);const closeAccount=()=>{setRegisterAccountId(null);setOpenAccountId(null)};const navigate=(nextTab:Tab)=>{setRegisterAccountId(null);setOpenAccountId(null);setTab(nextTab)};return <><style>{css}</style><div className="pc-shell"><Sidebar tab={tab} setTab={navigate}/><div className="pc-content"><Header/><main className="pc-main">{openAccountId?<div className="pc-account-detail"><AccountDetail accountId={openAccountId} onBack={closeAccount} onRegisterTrade={setRegisterAccountId}/></div>:tab==='dashboard'?<div className="pc-dashboard"><Dashboard onOpenAccount={setOpenAccountId} onRegisterTrade={setOpenAccountId}/></div>:tab==='calendario'?<CalendarScreen/>:tab==='mesas'?<div className="pc-mesas"><ProprietaryFirms/></div>:tab==='analise'?<div className="pc-intelligence"><Intelligence/></div>:tab==='jornada'?<div className="pc-journey"><Journey/></div>:<Finances/>}</main><MobileNav tab={tab} setTab={navigate}/></div></div>{registerAccountId&&<div className="pc-trade-modal"><div className="pc-trade-modal-card"><button onClick={()=>setRegisterAccountId(null)} aria-label="Fechar registro" className="absolute right-3 top-3 z-20 flex h-9 w-9 items-center justify-center rounded-full border border-[#3A321B] bg-[#111116]/90 text-[#D4AF37] backdrop-blur hover:bg-[#19170E]"><X size={18}/></button><div className="pc-trade-modal-scroll"><RegisterTrade accountId={registerAccountId} onBack={()=>setRegisterAccountId(null)}/></div></div></div>}</>}
// TEMPORÁRIO (apenas para visualizar o Preview): ignora o bloqueio do Supabase.
// Reverter para `false` antes de publicar em produção.
const PREVIEW_BYPASS_AUTH = true;
function Root(){const {session,loading}=useAuth();useEffect(()=>{if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});},[]);if(loading&&!PREVIEW_BYPASS_AUTH)return <div style={{minHeight:'100vh',background:'#0B0B0D',display:'grid',placeItems:'center',color:'#fff'}}>Carregando...</div>;if(!session&&!PREVIEW_BYPASS_AUTH)return <AuthScreen/>;return <AppProvider><AppContent/></AppProvider>}
export default function App(){return <AuthProvider><Root/></AuthProvider>}
