import { useEffect, useState } from 'react';
import { Home, CalendarDays, Brain, Banknote, Footprints, Calendar, X } from 'lucide-react';
import { AppProvider } from './store';
import { AuthProvider, useAuth } from './auth';
import { AuthScreen } from './AuthScreen';
import { Dashboard } from './src/screens/Dashboard';
import { AccountDetail } from './src/screens/AccountDetail';
import { Calendar as CalendarScreen } from './src/screens/Calendar';
import { Journey } from './src/screens/Journey';
import { Finances } from './src/screens/Finances';
import { Intelligence } from './src/screens/Intelligence';
import { RegisterTrade } from './src/screens/RegisterTrade';

type Tab = 'dashboard'|'calendario'|'jornada'|'financas'|'analise';
const TABS = [{id:'dashboard' as Tab,label:'Início',icon:Home},{id:'calendario' as Tab,label:'Calendário',icon:CalendarDays},{id:'analise' as Tab,label:'Inteligência',icon:Brain},{id:'financas' as Tab,label:'Financeiro',icon:Banknote},{id:'jornada' as Tab,label:'Jornada',icon:Footprints}];

const css=`.pc-shell{min-height:100vh;background:#0B0B0D;color:#eee}.pc-sidebar{display:none}.pc-content{min-height:100vh}.pc-header{height:70px;border-bottom:1px solid #24242B;background:#0B0B0D}.pc-header-inner{height:100%;display:flex;align-items:center;justify-content:space-between;padding:0 20px}.pc-main{max-width:1180px;margin:0 auto;padding:20px 16px 90px}.pc-mobile-nav{display:block}.pc-journey{width:100%}
@media(min-width:900px){.pc-sidebar{display:flex;position:fixed;inset:0 auto 0 0;width:220px;z-index:50;flex-direction:column;padding:24px 16px;background:#0E0E11;border-right:1px solid #24242B}.pc-content{margin-left:220px}.pc-header{height:68px}.pc-header-inner{padding:0 24px;max-width:none;margin:0}.pc-main{max-width:1180px;margin:0 auto;padding:24px 28px 50px}.pc-dashboard{max-width:1180px!important;margin:0 auto!important}.pc-dashboard>div:first-child{max-width:1180px;margin-left:auto;margin-right:auto}.pc-dashboard>section{max-width:1180px;margin-left:auto;margin-right:auto}
/* Desktop density: aproveita a largura sem transformar o app em um mobile ampliado. */
.pc-calendar{padding-top:8px!important;padding-left:0!important;padding-right:0!important}.pc-calendar>.mx-auto{max-width:1120px!important;space-y:3!important}.pc-calendar section{padding:18px!important}.pc-calendar section:first-of-type{padding:18px!important}.pc-calendar .mb-6{margin-bottom:14px!important}.pc-calendar .grid.grid-cols-7{gap:5px!important}.pc-calendar .grid.grid-cols-7>button{border-radius:10px!important}.pc-calendar .pc-calendar-summary>div{min-height:76px!important;padding:10px!important}
.pc-journey>.journey-inner{}
.pc-journey section:first-child{min-height:300px!important;border-radius:22px!important}.pc-journey section:first-child h1{font-size:21px!important}.pc-journey section:first-child .mt-\[112px\]{margin-top:72px!important}.pc-journey section:first-child svg{max-width:34px}.pc-journey section:nth-child(2){padding:14px 18px!important;border-radius:18px!important}.pc-journey section:nth-child(2) .h-12{width:40px!important;height:40px!important}.pc-journey section:nth-child(2) .text-\[22px\]{font-size:18px!important}.pc-journey section:nth-child(3){gap:10px!important}.pc-journey section:nth-child(3) button{min-height:108px!important;border-radius:18px!important}.pc-journey section:nth-child(3) button>div{min-height:108px!important}.pc-journey section:nth-child(3) button .w-\[92px\]{width:70px!important}.pc-journey section:nth-child(3) button .h-12{width:40px!important;height:40px!important}.pc-journey section:nth-child(3) button h2{font-size:17px!important}.pc-journey section:nth-child(3) button .text-\[31px\]{font-size:25px!important}
.pc-mobile-nav{display:none}}
@media(min-width:900px) and (max-width:1200px){.pc-main{padding-left:20px;padding-right:20px}.pc-sidebar{width:208px}.pc-content{margin-left:208px}.pc-journey{max-width:760px;margin:0 auto}.pc-calendar>.mx-auto{max-width:1000px!important}}
@media(min-width:1201px){.pc-journey{max-width:820px;margin:0 auto}}
.pc-trade-modal{position:fixed;inset:0;z-index:10000;display:grid;place-items:center;background:rgba(0,0,0,.72);backdrop-filter:blur(8px);padding:16px}.pc-trade-modal-card{position:relative;width:min(100%,480px);max-height:min(88vh,760px);overflow:hidden;border:1px solid #4A3C16;border-radius:24px;background:#0A0A0D;box-shadow:0 28px 90px rgba(0,0,0,.75),0 0 40px rgba(212,175,55,.06)}.pc-trade-modal-scroll{height:100%;max-height:min(88vh,760px);overflow-y:auto;overscroll-behavior:contain}.pc-trade-modal .register-trade{max-width:none!important;padding:0 16px 22px!important}.pc-trade-modal .register-trade>div:first-child{padding-top:16px!important}.pc-trade-modal .register-trade>div:first-child>button:first-child{visibility:hidden;width:40px}.pc-trade-modal .register-trade>div:first-child>div:last-child{visibility:hidden}.pc-trade-modal .register-trade>div:first-child h1{font-size:18px!important;text-transform:uppercase;letter-spacing:.08em}.pc-trade-modal .register-trade>div:first-child p{display:none}.pc-trade-modal .register-trade>section:first-of-type{margin-top:10px!important;padding:14px!important;border-radius:18px!important}.pc-trade-modal .register-trade>section:first-of-type>div{gap:12px!important}.pc-trade-modal .register-trade>section:first-of-type .h-24{width:48px!important;height:48px!important;border-radius:14px!important}.pc-trade-modal .register-trade>section:first-of-type .text-4xl{font-size:20px!important}.pc-trade-modal .register-trade>section:first-of-type h2{font-size:15px!important}.pc-trade-modal .register-trade>section:first-of-type .mt-4{margin-top:8px!important}.pc-trade-modal .register-trade>section:nth-of-type(2){margin-top:12px!important;padding:16px!important;border-radius:18px!important}.pc-trade-modal .register-trade>section:nth-of-type(2)>div:nth-of-type(2){grid-template-columns:1fr!important;gap:12px!important;margin-top:14px!important}.pc-trade-modal .register-trade>section:nth-of-type(2)>div:nth-of-type(5){grid-template-columns:repeat(3,minmax(0,1fr))!important}.pc-trade-modal .register-trade>section:nth-of-type(2) .h-16{height:52px!important}.pc-trade-modal .register-trade>section:nth-of-type(2) textarea{min-height:100px!important}.pc-trade-modal .register-trade>section:nth-of-type(2) .my-6{margin-top:14px!important;margin-bottom:14px!important}.pc-trade-modal .register-trade>button{height:58px!important;margin-top:12px!important;font-size:15px!important}.pc-trade-modal .register-trade>div:last-child{display:none}@media(max-width:520px){.pc-trade-modal{padding:8px}.pc-trade-modal-card{max-height:92vh;border-radius:20px}.pc-trade-modal-scroll{max-height:92vh}.pc-trade-modal .register-trade{padding-left:12px!important;padding-right:12px!important}.pc-trade-modal .register-trade>section:nth-of-type(2){padding:14px!important}}
`;
function NavItems({tab,setTab}:{tab:Tab;setTab:(tab:Tab)=>void}){return <nav style={{display:'grid',gap:4}}>{TABS.map(({id,label,icon:Icon})=>{const a=tab===id;return <button key={id} onClick={()=>setTab(id)} style={{display:'flex',alignItems:'center',gap:12,width:'100%',padding:'11px 13px',border:0,borderRadius:12,background:a?'#1A1A20':'transparent',color:a?'#D4AF37':'#777782',fontSize:13,fontWeight:700,textAlign:'left',cursor:'pointer'}}><Icon size={18}/>{label}</button>})}</nav>}
function Sidebar({tab,setTab}:{tab:Tab;setTab:(tab:Tab)=>void}){return <aside className="pc-sidebar"><div style={{display:'flex',alignItems:'center',gap:11,padding:'0 8px',marginBottom:30}}><div style={{width:36,height:36,borderRadius:10,display:'grid',placeItems:'center',background:'linear-gradient(135deg,#D4AF37,#9E7D19)',color:'#090909',fontWeight:900}}>P</div><div><div style={{fontSize:14,fontWeight:900,color:'#fff'}}>PROPCONTROL</div><div style={{fontSize:7,color:'#D4AF37',letterSpacing:'.2em',fontWeight:800}}>TRADING CONTROL</div></div></div><div style={{fontSize:9,color:'#55555F',fontWeight:800,letterSpacing:'.16em',padding:'0 13px 9px'}}>MENU PRINCIPAL</div><NavItems tab={tab} setTab={setTab}/><div style={{marginTop:'auto',padding:'12px 13px',borderTop:'1px solid #24242B',fontSize:10,color:'#55555F'}}>Gestão profissional de contas prop.</div></aside>}
function MobileNav({tab,setTab}:{tab:Tab;setTab:(tab:Tab)=>void}){return <nav className="pc-mobile-nav" style={{position:'fixed',bottom:0,left:0,right:0,zIndex:9999,height:74,background:'#0B0B0D',borderTop:'1px solid #292930'}}><div style={{maxWidth:520,height:74,margin:'0 auto',display:'grid',gridTemplateColumns:'repeat(5,1fr)',alignItems:'center'}}>{TABS.map(({id,label,icon:Icon})=>{const a=tab===id;return <button key={id} onClick={()=>setTab(id)} style={{height:62,border:0,background:'transparent',color:a?'#D4AF37':'#73737D',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',gap:5,fontSize:10,fontWeight:700}}><Icon size={20}/><span>{label}</span></button>})}</div></nav>}
function Header(){const now=new Date();return <header className="pc-header"><div className="pc-header-inner"><div><div style={{fontSize:19,fontWeight:850,color:'#fff'}}>Boa {now.getHours()<12?'dia':now.getHours()<18?'tarde':'noite'}, Weslley! 👊</div><div style={{fontSize:11,color:'#666671',marginTop:3}}>Foco total na execução. Um trade de cada vez.</div></div><div style={{display:'flex',alignItems:'center',gap:8,padding:'9px 12px',border:'1px solid #34343C',borderRadius:11,color:'#A3A3AD',fontSize:11}}><Calendar size={14} color="#D4AF37"/>{now.toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long',year:'numeric'})}</div></div></header>}
function AppContent(){const [tab,setTab]=useState<Tab>('dashboard');const [openAccountId,setOpenAccountId]=useState<string|null>(null);const [registerAccountId,setRegisterAccountId]=useState<string|null>(null);const closeAccount=()=>{setRegisterAccountId(null);setOpenAccountId(null)};const navigate=(nextTab:Tab)=>{setRegisterAccountId(null);setOpenAccountId(null);setTab(nextTab)};return <><style>{css}</style><div className="pc-shell"><Sidebar tab={tab} setTab={navigate}/><div className="pc-content"><Header/><main className="pc-main">{openAccountId?<AccountDetail accountId={openAccountId} onBack={closeAccount} onRegisterTrade={setRegisterAccountId}/>:tab==='dashboard'?<div className="pc-dashboard"><Dashboard onOpenAccount={setOpenAccountId} onRegisterTrade={setOpenAccountId}/></div>:tab==='calendario'?<CalendarScreen/>:tab==='analise'?<Intelligence/>:tab==='jornada'?<div className="pc-journey"><Journey/></div>:<Finances/>}</main><MobileNav tab={tab} setTab={navigate}/></div></div>{registerAccountId&&<div className="pc-trade-modal"><div className="pc-trade-modal-card"><button onClick={()=>setRegisterAccountId(null)} aria-label="Fechar registro" className="absolute right-3 top-3 z-20 flex h-9 w-9 items-center justify-center rounded-full border border-[#3A321B] bg-[#111116]/90 text-[#D4AF37] backdrop-blur hover:bg-[#19170E]"><X size={18}/></button><div className="pc-trade-modal-scroll"><RegisterTrade accountId={registerAccountId} onBack={()=>setRegisterAccountId(null)}/></div></div></div>}</>}
function Root(){const {session,loading}=useAuth();useEffect(()=>{if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});},[]);if(loading)return <div style={{minHeight:'100vh',background:'#0B0B0D',display:'grid',placeItems:'center',color:'#fff'}}>Carregando...</div>;if(!session)return <AuthScreen/>;return <AppProvider><AppContent/></AppProvider>}
export default function App(){return <AuthProvider><Root/></AuthProvider>}
