import { useEffect, useState } from 'react';
import { Home, CalendarDays, Brain, Banknote, Footprints, Calendar, X, Building2 } from 'lucide-react';
import { AppProvider } from './store';
import { AuthProvider, useAuth } from './auth';
import { AuthScreen } from './AuthScreen';
import { Dashboard } from './src/screens/Dashboard';
import { AccountDetail } from './src/screens/AccountDetail';
import { Calendar as CalendarScreen } from './src/screens/Calendar';
import { Journey } from './src/screens/Journey';
import { Finances } from './src/screens/Finances';
import { Intelligence } from './src/screens/Intelligence';
import { RegisterTrade } from './src/screens/RegisterTrade';
import { ProprietaryFirms } from './src/screens/ProprietaryFirms';

type Tab='dashboard'|'calendario'|'mesas'|'analise'|'financas'|'jornada';
const TABS=[{id:'dashboard' as Tab,label:'Início',icon:Home},{id:'calendario' as Tab,label:'Calendário',icon:CalendarDays},{id:'mesas' as Tab,label:'Mesas',icon:Building2},{id:'analise' as Tab,label:'Inteligência',icon:Brain},{id:'financas' as Tab,label:'Financeiro',icon:Banknote},{id:'jornada' as Tab,label:'Jornada',icon:Footprints}];
const css=`.pc-shell{min-height:100vh;background:#0B0B0D;color:#eee}.pc-sidebar{display:none}.pc-content{min-height:100vh}.pc-header{height:70px;border-bottom:1px solid #24242B;background:#0B0B0D}.pc-header-inner{height:100%;display:flex;align-items:center;justify-content:space-between;padding:0 20px}.pc-main{max-width:1180px;margin:0 auto;padding:20px 16px 90px}.pc-mobile-nav{display:block}.pc-main>section{max-width:820px;margin:0 auto}@media(min-width:900px){.pc-sidebar{display:flex;position:fixed;inset:0 auto 0 0;width:220px;z-index:50;flex-direction:column;padding:24px 16px;background:#0E0E11;border-right:1px solid #24242B}.pc-content{margin-left:220px}.pc-header{height:68px}.pc-header-inner{padding:0 24px}.pc-main{max-width:860px;margin:0;padding:24px 16px 50px}.pc-mobile-nav{display:none}}.pc-trade-modal{position:fixed;inset:0;z-index:10000;display:grid;place-items:center;background:rgba(0,0,0,.72);backdrop-filter:blur(8px);padding:16px}.pc-trade-modal-card{position:relative;width:min(100%,480px);max-height:88vh;overflow:hidden;border:1px solid #4A3C16;border-radius:24px;background:#0A0A0D;box-shadow:0 28px 90px rgba(0,0,0,.75)}.pc-trade-modal-scroll{height:100%;max-height:88vh;overflow-y:auto}`;
function NavItems({tab,setTab}:{tab:Tab;setTab:(t:Tab)=>void}){return <nav style={{display:'grid',gap:4}}>{TABS.map(({id,label,icon:Icon})=>{const a=tab===id;return <button key={id} onClick={()=>setTab(id)} style={{display:'flex',alignItems:'center',gap:12,width:'100%',padding:'11px 13px',border:0,borderRadius:12,background:a?'#1A1A20':'transparent',color:a?'#D4AF37':'#777782',fontSize:13,fontWeight:700,textAlign:'left',cursor:'pointer'}}><Icon size={18}/>{label}</button>})}</nav>}
function Sidebar({tab,setTab}:{tab:Tab;setTab:(t:Tab)=>void}){return <aside className="pc-sidebar"><div style={{display:'flex',alignItems:'center',gap:11,padding:'0 8px',marginBottom:30}}><div style={{width:36,height:36,borderRadius:10,display:'grid',placeItems:'center',background:'linear-gradient(135deg,#D4AF37,#9E7D19)',color:'#090909',fontWeight:900}}>P</div><div><div style={{fontSize:14,fontWeight:900,color:'#fff'}}>PROPCONTROL</div><div style={{fontSize:7,color:'#D4AF37',letterSpacing:'.2em',fontWeight:800}}>TRADING CONTROL</div></div></div><div style={{fontSize:9,color:'#55555F',fontWeight:800,letterSpacing:'.16em',padding:'0 13px 9px'}}>MENU PRINCIPAL</div><NavItems tab={tab} setTab={setTab}/><div style={{marginTop:'auto',padding:'12px 13px',borderTop:'1px solid #24242B',fontSize:10,color:'#55555F'}}>Gestão profissional de contas prop.</div></aside>}
function MobileNav({tab,setTab}:{tab:Tab;setTab:(t:Tab)=>void}){return <nav className="pc-mobile-nav" style={{position:'fixed',bottom:0,left:0,right:0,zIndex:9999,height:74,background:'#0B0B0D',borderTop:'1px solid #292930'}}><div style={{maxWidth:620,height:74,margin:'0 auto',display:'grid',gridTemplateColumns:'repeat(6,1fr)',alignItems:'center'}}>{TABS.map(({id,label,icon:Icon})=>{const a=tab===id;return <button key={id} onClick={()=>setTab(id)} style={{height:62,border:0,background:'transparent',color:a?'#D4AF37':'#73737D',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',gap:5,fontSize:9,fontWeight:700}}><Icon size={19}/><span>{label}</span></button>})}</div></nav>}
function Header(){const now=new Date();return <header className="pc-header"><div className="pc-header-inner"><div><div style={{fontSize:19,fontWeight:850,color:'#fff'}}>Boa {now.getHours()<12?'dia':now.getHours()<18?'tarde':'noite'}, Weslley! 👊</div><div style={{fontSize:11,color:'#666671',marginTop:3}}>Foco total na execução. Um trade de cada vez.</div></div><div style={{display:'flex',alignItems:'center',gap:8,padding:'9px 12px',border:'1px solid #34343C',borderRadius:11,color:'#A3A3AD',fontSize:11}}><Calendar size={14} color="#D4AF37"/>{now.toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long',year:'numeric'})}</div></div></header>}
function AppContent(){const[tab,setTab]=useState<Tab>('dashboard');const[openAccountId,setOpenAccountId]=useState<string|null>(null);const[registerAccountId,setRegisterAccountId]=useState<string|null>(null);const closeAccount=()=>{setRegisterAccountId(null);setOpenAccountId(null)};const navigate=(next:Tab)=>{setRegisterAccountId(null);setOpenAccountId(null);setTab(next)};return <><style>{css}</style><div className="pc-shell"><Sidebar tab={tab} setTab={navigate}/><div className="pc-content"><Header/><main className="pc-main">{openAccountId?<AccountDetail accountId={openAccountId} onBack={closeAccount} onRegisterTrade={setRegisterAccountId}/>:tab==='dashboard'?<Dashboard onOpenAccount={setOpenAccountId} onRegisterTrade={setRegisterAccountId}/>:tab==='calendario'?<CalendarScreen/>:tab==='mesas'?<ProprietaryFirms/>:tab==='analise'?<Intelligence/>:tab==='jornada'?<Journey/>:<Finances/>}</main><MobileNav tab={tab} setTab={navigate}/></div></div>{registerAccountId&&<div className="pc-trade-modal"><div className="pc-trade-modal-card"><button onClick={()=>setRegisterAccountId(null)} aria-label="Fechar registro" className="absolute right-3 top-3 z-20 flex h-9 w-9 items-center justify-center rounded-full border border-[#3A321B] bg-[#111116]/90 text-[#D4AF37]"><X size={18}/></button><div className="pc-trade-modal-scroll"><RegisterTrade accountId={registerAccountId} onBack={()=>setRegisterAccountId(null)}/></div></div></div>}</>}
function Root(){const{session,loading}=useAuth();useEffect(()=>{if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{})},[]);if(loading)return <div style={{minHeight:'100vh',background:'#0B0B0D',display:'grid',placeItems:'center',color:'#fff'}}>Carregando...</div>;if(!session)return <AuthScreen/>;return <AppProvider><AppContent/></AppProvider>}
export default function AppMulti(){return <AuthProvider><Root/></AuthProvider>}
