import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';
import type { Account, AccountRuleSnapshot, AccountSize, AccountStatus, AppData, Movement, MovementType, Trade } from './types';
import { PNL_RULES } from './types';
import { OFFICIAL_PROP_FIRMS, hydrateRules, type PhaseRules, type PropFirmConfig } from './propConfig';
import { seedData } from './seed';
import { rotateAccount } from './rotation';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/lib/auth';

export interface PropProgram { id: string; firmId: string; name: string; sizes: AccountSize[]; phases: { phase:number; name:string; rules:PhaseRules }[]; }
export interface PropFirm { id: string; name: string; isOfficial: boolean; programs: PropProgram[]; }
interface NewAccountInput { name:string; code:string; size:AccountSize; propProgramId?:string; propFirmName?:string; propProgramName?:string; rulesSnapshot?:AccountRuleSnapshot[]; }
interface NewTradeInput { accountId:string; asset:Trade['asset']; context:Trade['context']; timeframe:Trade['timeframe']; result:Trade['result']; amount:number; note?:string; }
interface NewMovementInput { type:MovementType; amount:number; description:string; }
interface AppContextValue { data:AppData; accounts:Account[]; trades:Trade[]; movements:Movement[]; propFirms:PropFirm[]; loading:boolean; addAccount:(input:NewAccountInput)=>void; addTrade:(input:NewTradeInput)=>Promise<{ok:boolean;error?:string}>; setAccountStatus:(id:string,status:AccountStatus)=>void; addMovement:(input:NewMovementInput)=>void; deleteMovement:(id:string)=>void; deleteTrade:(id:string)=>void; deleteAccount:(id:string)=>void; createPropFirm:(input:PropFirmConfig)=>Promise<void>; }
const AppContext=createContext<AppContextValue|null>(null);
const EMPTY_DATA:AppData={accounts:[],trades:[],movements:[],seeded:true};

export function AppProvider({children}:{children:ReactNode}){
  const {user}=useAuth(); const [data,setData]=useState<AppData>(EMPTY_DATA); const [propFirms,setPropFirms]=useState<PropFirm[]>([]); const [loading,setLoading]=useState(true);
  useEffect(()=>{ if(!user){setData(EMPTY_DATA);setPropFirms([]);setLoading(false);return;} let cancelled=false; setLoading(true);
    (async()=>{
      const [accRes,tradeRes,movRes,firmRes,programRes]=await Promise.all([
        supabase.from('accounts').select('*'),supabase.from('trades').select('*'),supabase.from('movements').select('*'),supabase.from('prop_firms').select('*'),supabase.from('prop_programs').select('*')
      ]);
      if(cancelled)return;
      const accounts=(accRes.data||[]).map(rowToAccount); const trades=(tradeRes.data||[]).map(rowToTrade); const movements=(movRes.data||[]).map(rowToMovement);
      let firms=mapPropFirms(firmRes.data||[],programRes.data||[]);
      if(firms.length===0){ firms=await seedOfficialPropFirms(); }
      if(accounts.length===0&&trades.length===0&&movements.length===0){const seeded=seedData();await seedToSupabase(seeded);if(cancelled)return;setData(seeded);}else setData({accounts,trades,movements,seeded:true});
      setPropFirms(firms);setLoading(false);
    })(); return()=>{cancelled=true;};
  },[user]);
  useEffect(()=>{if(!user)return;const channel=supabase.channel('propcontrol_changes').on('postgres_changes',{event:'*',schema:'public',table:'accounts'},p=>setData(prev=>applyChange(prev,'accounts',p))).on('postgres_changes',{event:'*',schema:'public',table:'trades'},p=>setData(prev=>applyChange(prev,'trades',p))).on('postgres_changes',{event:'*',schema:'public',table:'movements'},p=>setData(prev=>applyChange(prev,'movements',p))).subscribe();return()=>{supabase.removeChannel(channel);};},[user]);
  const value=useMemo<AppContextValue>(()=>{
    const addAccount:AppContextValue['addAccount']=input=>{const status:AccountStatus='Avaliacao';const sameCat=data.accounts.filter(a=>a.status===status);const maxOrder=sameCat.length?Math.max(...sameCat.map(a=>a.queueOrder):-1);const acc:Account={id:crypto.randomUUID(),name:input.name,code:input.code,size:input.size,status,createdAt:Date.now(),queueOrder:maxOrder+1,currentPhase:1,propProgramId:input.propProgramId,propFirmName:input.propFirmName,propProgramName:input.propProgramName,rulesSnapshot:input.rulesSnapshot};setData(prev=>({...prev,accounts:[...prev.accounts,acc]}));supabase.from('accounts').insert(accountToRow(acc)).then(({error})=>{if(error)console.error('Erro ao salvar conta:',error);});};
    const addTrade:AppContextValue['addTrade']=async input=>{const trade:Trade={id:crypto.randomUUID(),accountId:input.accountId,asset:input.asset,context:input.context,timeframe:input.timeframe,result:input.result,amount:input.amount,note:input.note,timestamp:Date.now()};const account=data.accounts.find(a=>a.id===input.accountId);let accounts=rotateAccount(data.accounts,input.accountId);let fundedAt:number|undefined;
      if(account&&account.status==='Avaliacao'){const accountTrades=[...data.trades,trade].filter(t=>t.accountId===input.accountId);const totalProfit=accountTrades.reduce((sum,t)=>sum+t.amount,0);const phase=account.currentPhase??1;const snapshots=account.rulesSnapshot;const target=snapshots?.[phase-1]?.target??PNL_RULES[account.size].target;const phaseCount=snapshots?.length??1;
        if(target!=null&&totalProfit>=target){if(phase<phaseCount){accounts=accounts.map(a=>a.id===input.accountId?{...a,currentPhase:phase+1}:a);}else{const fundedPeers=accounts.filter(a=>a.status==='Financiada'&&a.id!==input.accountId);const maxOrder=fundedPeers.length?Math.max(...fundedPeers.map(a=>a.queueOrder):-1);fundedAt=trade.timestamp+1;accounts=accounts.map(a=>a.id===input.accountId?{...a,status:'Financiada' as AccountStatus,queueOrder:maxOrder+1,fundedAt}:a);}}
      }
      const {error:tradeError}=await supabase.from('trades').insert(tradeToRow(trade));if(tradeError){console.error('Erro ao salvar trade:',tradeError);return{ok:false,error:tradeError.message};}
      const updatedAcc=accounts.find(a=>a.id===input.accountId);if(updatedAcc){const {error}=await supabase.from('accounts').update({queue_order:updatedAcc.queueOrder,status:updatedAcc.status,funded_at:updatedAcc.fundedAt??null,current_phase:updatedAcc.currentPhase??1}).eq('id',input.accountId);if(error)console.error('Erro ao atualizar conta:',error);}
      setData(prev=>({...prev,trades:prev.trades.some(t=>t.id===trade.id)?prev.trades:[trade,...prev.trades],accounts}));return{ok:true};
    };
    const setAccountStatus:AppContextValue['setAccountStatus']=(id,status)=>{setData(prev=>{const sameCat=prev.accounts.filter(a=>a.status===status&&a.id!==id);const maxOrder=sameCat.length?Math.max(...sameCat.map(a=>a.queueOrder):-1);const accounts=prev.accounts.map(a=>a.id===id?{...a,status,queueOrder:maxOrder+1,fundedAt:status==='Financiada'?(a.fundedAt??Date.now()+1):undefined}:a);const updated=accounts.find(a=>a.id===id);if(updated)supabase.from('accounts').update({status:updated.status,queue_order:updated.queueOrder,funded_at:updated.fundedAt??null}).eq('id',id);return{...prev,accounts};});};
    const addMovement:AppContextValue['addMovement']=input=>{const movement:Movement={id:crypto.randomUUID(),type:input.type,amount:input.amount,description:input.description,timestamp:Date.now()};setData(prev=>({...prev,movements:[movement,...prev.movements]}));supabase.from('movements').insert(movementToRow(movement));};
    const deleteMovement:AppContextValue['deleteMovement']=id=>{setData(prev=>({...prev,movements:prev.movements.filter(m=>m.id!==id)}));supabase.from('movements').delete().eq('id',id);};
    const deleteTrade:AppContextValue['deleteTrade']=id=>{setData(prev=>({...prev,trades:prev.trades.filter(t=>t.id!==id)}));supabase.from('trades').delete().eq('id',id);};
    const deleteAccount:AppContextValue['deleteAccount']=id=>{setData(prev=>({...prev,accounts:prev.accounts.filter(a=>a.id!==id),trades:prev.trades.filter(t=>t.accountId!==id)}));supabase.from('accounts').delete().eq('id',id);};
    const createPropFirm:AppContextValue['createPropFirm']=async input=>{const firmId=crypto.randomUUID();const {error:firmError}=await supabase.from('prop_firms').insert({id:firmId,name:input.name,is_official:false});if(firmError)throw firmError;const programs:PropProgram[]=await Promise.all(input.programs.map(async p=>{const id=crypto.randomUUID();const {error}=await supabase.from('prop_programs').insert({id,firm_id:firmId,name:p.name,sizes:p.sizes,phases:p.phases});if(error)throw error;return{id,firmId,name:p.name,sizes:p.sizes,phases:p.phases};}));setPropFirms(prev=>[...prev,{id:firmId,name:input.name,isOfficial:false,programs}]);};
    return{data,accounts:data.accounts,trades:data.trades,movements:data.movements,propFirms,loading,addAccount,addTrade,setAccountStatus,addMovement,deleteMovement,deleteTrade,deleteAccount,createPropFirm};
  },[data,loading,user,propFirms]);
  return<AppContext.Provider value={value}>{children}</AppContext.Provider>;
}
export function useApp():AppContextValue{const ctx=useContext(AppContext);if(!ctx)throw new Error('useApp must be used within AppProvider');return ctx;}

async function seedOfficialPropFirms():Promise<PropFirm[]>{const result:PropFirm[]=[];for(const firm of OFFICIAL_PROP_FIRMS){const firmId=crypto.randomUUID();const {error}=await supabase.from('prop_firms').insert({id:firmId,name:firm.name,is_official:true});if(error){console.error('Erro ao cadastrar mesa oficial:',error);continue;}const programs:PropProgram[]=[];for(const p of firm.programs){const id=crypto.randomUUID();const phases=p.phases;const {error:programError}=await supabase.from('prop_programs').insert({id,firm_id:firmId,name:p.name,sizes:p.sizes,phases});if(programError){console.error('Erro ao cadastrar programa:',programError);continue;}programs.push({id,firmId,name:p.name,sizes:p.sizes,phases});}result.push({id:firmId,name:firm.name,isOfficial:true,programs});}return result;}
function mapPropFirms(firmRows:any[],programRows:any[]):PropFirm[]{return firmRows.map(f=>({id:f.id,name:f.name,isOfficial:Boolean(f.is_official),programs:programRows.filter(p=>p.firm_id===f.id).map(p=>({id:p.id,firmId:p.firm_id,name:p.name,sizes:p.sizes as AccountSize[],phases:p.phases||[]}))}));}
interface AccountRow{id:string;name:string;code:string;size:string;status:string;queue_order:number;created_at:number;funded_at:number|null;prop_program_id?:string|null;current_phase?:number|null;rules_snapshot?:AccountRuleSnapshot[]|null;prop_firm_name?:string|null;prop_program_name?:string|null;}
function rowToAccount(r:AccountRow):Account{return{id:r.id,name:r.name,code:r.code,size:r.size as AccountSize,status:r.status as AccountStatus,queueOrder:r.queue_order,createdAt:r.created_at,fundedAt:r.funded_at??undefined,propProgramId:r.prop_program_id??undefined,currentPhase:r.current_phase??1,rulesSnapshot:r.rules_snapshot??undefined,propFirmName:r.prop_firm_name??undefined,propProgramName:r.prop_program_name??undefined};}
function accountToRow(a:Account):AccountRow{return{id:a.id,name:a.name,code:a.code,size:a.size,status:a.status,queue_order:a.queueOrder,created_at:a.createdAt,funded_at:a.fundedAt??null,prop_program_id:a.propProgramId??null,current_phase:a.currentPhase??1,rules_snapshot:a.rulesSnapshot??null,prop_firm_name:a.propFirmName??null,prop_program_name:a.propProgramName??null};}
interface TradeRow{id:string;account_id:string;asset:string;context:string;timeframe:string;result:string;amount:number;note:string|null;timestamp:number;}
function rowToTrade(r:TradeRow):Trade{return{id:r.id,accountId:r.account_id,asset:r.asset,context:r.context as Trade['context'],timeframe:r.timeframe as Trade['timeframe'],result:r.result as Trade['result'],amount:Number(r.amount),note:r.note??undefined,timestamp:r.timestamp};}
function tradeToRow(t:Trade):TradeRow{return{id:t.id,account_id:t.accountId,asset:t.asset,context:t.context,timeframe:t.timeframe,result:t.result,amount:t.amount,note:t.note??null,timestamp:t.timestamp};}
interface MovementRow{id:string;type:string;amount:number;description:string;timestamp:number;}
function rowToMovement(r:MovementRow):Movement{return{id:r.id,type:r.type as MovementType,amount:Number(r.amount),description:r.description,timestamp:r.timestamp};}
function movementToRow(m:Movement):MovementRow{return{id:m.id,type:m.type,amount:m.amount,description:m.description,timestamp:m.timestamp};}
type Payload={eventType:'INSERT'|'UPDATE'|'DELETE';old:Record<string,unknown>|null;new:Record<string,unknown>|null};
function applyChange(prev:AppData,table:'accounts'|'trades'|'movements',payload:Payload):AppData{const{eventType,old,new:newRec}=payload;if(table==='accounts'){if(eventType==='DELETE'){const id=(old as AccountRow|null)?.id;return id?{...prev,accounts:prev.accounts.filter(a=>a.id!==id)}:prev;}const acc=rowToAccount(newRec as unknown as AccountRow);if(eventType==='INSERT')return prev.accounts.some(a=>a.id===acc.id)?prev:{...prev,accounts:[...prev.accounts,acc]};return{...prev,accounts:prev.accounts.map(a=>a.id===acc.id?acc:a)};}if(table==='trades'){if(eventType==='DELETE'){const id=(old as TradeRow|null)?.id;return id?{...prev,trades:prev.trades.filter(t=>t.id!==id)}:prev;}const trade=rowToTrade(newRec as unknown as TradeRow);if(eventType==='INSERT')return prev.trades.some(t=>t.id===trade.id)?prev:{...prev,trades:[trade,...prev.trades]};return{...prev,trades:prev.trades.map(t=>t.id===trade.id?trade:t)};}if(eventType==='DELETE'){const id=(old as MovementRow|null)?.id;return id?{...prev,movements:prev.movements.filter(m=>m.id!==id)}:prev;}const movement=rowToMovement(newRec as unknown as MovementRow);if(eventType==='INSERT')return prev.movements.some(m=>m.id===movement.id)?prev:{...prev,movements:[movement,...prev.movements]};return{...prev,movements:prev.movements.map(m=>m.id===movement.id?movement:m)};}
async function seedToSupabase(seeded:AppData):Promise<void>{await supabase.from('accounts').insert(seeded.accounts.map(accountToRow));await supabase.from('trades').insert(seeded.trades.map(tradeToRow));await supabase.from('movements').insert(seeded.movements.map(movementToRow));}
