import { useState } from 'react';
import { ArrowLeft, Check, Trash2, AlertTriangle, TrendingUp, Shield, Target, CalendarDays, Wallet, Gauge, CircleDollarSign } from 'lucide-react';
import { useApp } from '@/store';
import type { Account, Trade, AccountStatus } from '@/types';
import { ACCOUNT_STATUSES, SIZE_COLORS } from '@/types';
import { formatCurrency, formatSignedCurrency, formatDateTime } from '@/dates';

const PNL_RULES: Record<string, { capital:number; target:number; drawdown:number; floor:number; daily:number }> = {
  '25K': { capital:25000, target:1500, drawdown:1500, floor:23500, daily:750 },
  '50K': { capital:50000, target:3000, drawdown:3000, floor:47000, daily:1500 },
  '100K': { capital:100000, target:6000, drawdown:6000, floor:94000, daily:3000 },
  '150K': { capital:150000, target:9000, drawdown:9000, floor:141000, daily:4500 },
};

export function AccountDetail({ accountId, onBack }: { accountId:string; onBack:()=>void }) {
  const { accounts, trades, setAccountStatus, deleteAccount } = useApp();
  const [confirmDelete,setConfirmDelete]=useState(false);
  const account=accounts.find(a=>a.id===accountId);
  if(!account) return <div className="p-6 text-white"><button onClick={onBack}>Voltar</button><p className="mt-4 text-gray-500">Conta não encontrada.</p></div>;
  const accountTrades=trades.filter(t=>t.accountId===accountId);
  return <div className="min-h-screen bg-[#0B0B0D] text-white pb-24">
    <header className="sticky top-0 z-30 border-b border-[#25252D] bg-[#0B0B0D]/95 backdrop-blur-xl px-5 py-4">
      <div className="max-w-6xl mx-auto flex items-center gap-4"><button onClick={onBack} className="w-10 h-10 rounded-xl bg-[#15151B] border border-[#2B2B34] grid place-items-center hover:border-[#D4AF37]"><ArrowLeft size={18}/></button><div className="flex-1"><div className="flex items-center gap-2"><span className={`w-2.5 h-2.5 rounded-full ${SIZE_COLORS[account.size]?.dot||'bg-[#D4AF37]'}`}/><h1 className="text-lg font-bold">Detalhes da Conta</h1></div><p className="text-xs text-gray-500 mt-0.5">{account.name} · PnL Global</p></div><div className="px-3 py-1.5 rounded-full bg-[#17150E] border border-[#5A4816] text-[#D4AF37] text-xs font-bold">{account.size}</div></div>
    </header>
    <main className="max-w-6xl mx-auto px-5 py-6 space-y-5">
      <section className="rounded-3xl border border-[#3B3115] bg-gradient-to-br from-[#17140B] to-[#101014] p-6 relative overflow-hidden"><div className="absolute -right-16 -top-20 w-56 h-56 rounded-full bg-[#D4AF37]/5 blur-3xl"/><div className="relative flex flex-col md:flex-row md:items-end md:justify-between gap-5"><div><p className="text-[11px] uppercase tracking-[.18em] text-[#9A8A55] font-bold">Conta operacional</p><h2 className="text-2xl md:text-3xl font-black mt-1">{account.name}</h2><p className="text-sm text-gray-500 mt-1">{account.propFirm} · Código {account.code}</p></div><StatusBadge status={account.status}/></div></section>
      <AccountOverview account={account} trades={accountTrades}/>
      <RulesPanel account={account} trades={accountTrades}/>
      <StatusPanel account={account} onChange={s=>setAccountStatus(accountId,s)}/>
      <TradeHistory trades={accountTrades}/>
      <button onClick={()=>setConfirmDelete(true)} className="w-full py-3.5 rounded-2xl border border-red-500/20 bg-red-500/5 text-red-400 font-bold"><Trash2 size={17} className="inline mr-2"/>Excluir Conta</button>
    </main>
    {confirmDelete&&<div className="fixed inset-0 z-50 bg-black/70 grid place-items-end md:place-items-center p-4" onClick={()=>setConfirmDelete(false)}><div className="w-full max-w-md rounded-3xl bg-[#15151B] border border-[#2B2B34] p-6" onClick={e=>e.stopPropagation()}><AlertTriangle className="text-red-400 mb-3"/><h3 className="text-lg font-bold">Excluir conta?</h3><p className="text-sm text-gray-500 mt-1 mb-5">A conta e seus trades serão removidos.</p><button onClick={()=>{deleteAccount(accountId);onBack()}} className="w-full py-3.5 rounded-2xl bg-red-500 text-white font-bold mb-2">Sim, excluir conta</button><button onClick={()=>setConfirmDelete(false)} className="w-full py-3.5 rounded-2xl bg-[#22222A] text-white">Cancelar</button></div></div>}
  </div>;
}

function AccountOverview({account,trades}:{account:Account;trades:Trade[]}){const r=PNL_RULES[account.size]||PNL_RULES['25K'];const pnl=trades.reduce((s,t)=>s+t.amount,0);const balance=r.capital+pnl;const dd=Math.max(0,r.capital-balance);const takes=trades.filter(t=>t.result==='Take').length;const stops=trades.filter(t=>t.result==='Stop').length;const bes=trades.filter(t=>t.result==='BE').length;const cards=[['Saldo atual',formatCurrency(balance),Wallet],['Resultado',formatSignedCurrency(pnl),TrendingUp],['Drawdown usado',formatCurrency(dd),Shield],['Trades',String(trades.length),Gauge]] as const;return <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{cards.map(([label,value,Icon],i)=><div key={label} className="rounded-2xl border border-[#27272F] bg-[#121217] p-4"><div className="flex items-center justify-between"><span className="text-[10px] uppercase tracking-wider text-gray-500 font-bold">{label}</span><Icon size={16} className={i===1&&pnl>=0?'text-[#D4AF37]':'text-gray-600'}/></div><div className={`text-xl font-black mt-3 ${i===1?(pnl>=0?'text-emerald-400':'text-red-400'):'text-white'}`}>{value}</div></div>)}<div className="col-span-2 lg:col-span-4 rounded-2xl border border-[#27272F] bg-[#121217] p-4"><div className="flex justify-between text-xs mb-2"><span className="text-gray-500">Trades por resultado</span><span className="text-gray-400">{takes} Take · {stops} Stop · {bes} BE</span></div><div className="h-2 rounded-full bg-[#24242B] overflow-hidden flex">{trades.length>0&&<><div className="bg-emerald-400" style={{width:`${takes/trades.length*100}%`}}/><div className="bg-red-400" style={{width:`${stops/trades.length*100}%`}}/><div className="bg-gray-500" style={{width:`${bes/trades.length*100}%`}}/></>}</div></div></div>}

function RulesPanel({account,trades}:{account:Account;trades:Trade[]}){const r=PNL_RULES[account.size]||PNL_RULES['25K'];const pnl=trades.reduce((s,t)=>s+t.amount,0);const balance=r.capital+pnl;const dd=Math.max(0,r.capital-balance);const phase=account.status==='Financiada'?2:1;const targetPct=Math.max(0,Math.min(100,pnl/r.target*100));const daily=phase===2?r.daily:0;const dailyText=phase===2?formatCurrency(daily):'Não Aplicável';const profitableDays=Array.from(new Set(trades.filter(t=>t.amount>0).map(t=>new Date(t.timestamp).toDateString()))).length;const maxDay=Math.max(0,...Object.values(trades.reduce((m,t)=>{const d=new Date(t.timestamp).toDateString();m[d]=(m[d]||0)+t.amount;return m} as Record<string,number>,{})));const concentration=r.target?maxDay/r.target*100:0;return <section className="rounded-3xl border border-[#27272F] bg-[#111116] overflow-hidden"><div className="p-5 border-b border-[#27272F] flex items-center justify-between"><div><h3 className="font-bold text-lg">Painel PnL Global</h3><p className="text-xs text-gray-500 mt-1">Regras e progresso da conta</p></div><span className="text-xs font-bold px-3 py-1.5 rounded-full bg-[#1A160A] text-[#D4AF37]">Fase {phase} · {phase===1?'Challenge':'Funded Pro'}</span></div><div className="p-5 grid md:grid-cols-2 gap-4"><MetricCard icon={Target} title="Meta de lucro" value={`${formatCurrency(Math.max(0,pnl))} / ${formatCurrency(r.target)}`} progress={targetPct}/><MetricCard icon={Shield} title="Drawdown estático" value={`${formatCurrency(dd)} / ${formatCurrency(r.drawdown)}`} progress={Math.min(100,dd/r.drawdown*100)} danger={dd>r.drawdown*0.75}/><MetricCard icon={CalendarDays} title="Dias lucrativos" value={`${profitableDays} / 5`} progress={Math.min(100,profitableDays/5*100)}/><MetricCard icon={CircleDollarSign} title="Perda diária · Fase 2" value={dailyText} progress={phase===2?0:40} muted={phase===1}/></div><div className="px-5 pb-5 grid grid-cols-2 md:grid-cols-4 gap-3"><Mini label="Capital inicial" value={formatCurrency(r.capital)}/><Mini label="Piso de ruína" value={formatCurrency(r.floor)}/><Mini label="Maior dia" value={formatCurrency(maxDay)}/><Mini label="Concentração" value={`${concentration.toFixed(1)}% ${concentration<=50?'✓':'✕'}`} bad={concentration>50}/></div></section>}
function MetricCard({icon:Icon,title,value,progress,muted,danger}:{icon:any;title:string;value:string;progress:number;muted?:boolean;danger?:boolean}){return <div className={`rounded-2xl border border-[#27272F] bg-[#15151B] p-4 ${muted?'opacity-60':''}`}><div className="flex items-center gap-2 text-xs text-gray-500"><Icon size={15}/>{title}</div><div className="mt-3 font-bold text-white">{value}</div><div className="h-1.5 mt-3 rounded-full bg-[#25252D] overflow-hidden"><div className={`h-full ${danger?'bg-red-400':'bg-[#D4AF37]'}`} style={{width:`${Math.max(0,Math.min(100,progress))}%`}}/></div></div>}
function Mini({label,value,bad}:{label:string;value:string;bad?:boolean}){return <div className="rounded-xl border border-[#27272F] bg-[#0E0E12] p-3"><div className="text-[10px] uppercase tracking-wider text-gray-600">{label}</div><div className={`mt-1 text-sm font-bold ${bad?'text-red-400':'text-gray-200'}`}>{value}</div></div>}
function StatusPanel({account,onChange}:{account:Account;onChange:(s:AccountStatus)=>void}){return <section className="rounded-3xl border border-[#27272F] bg-[#111116] p-5"><div className="flex items-center gap-2 mb-4"><Gauge size={17} className="text-[#D4AF37]"/><h3 className="font-bold">Status da conta</h3></div><div className="grid grid-cols-3 gap-2">{ACCOUNT_STATUSES.map(s=><button key={s} onClick={()=>onChange(s)} className={`py-3 rounded-xl border text-xs font-bold ${account.status===s?'bg-[#D4AF37] text-black border-[#D4AF37]':'bg-[#15151B] text-gray-500 border-[#27272F]'}`}>{s==='Avaliacao'?'Challenge':s==='Financiada'?'Funded Pro':s}</button>)}</div></section>}
function StatusBadge({status}:{status:string}){return <span className="px-3 py-1.5 rounded-full bg-[#17150E] border border-[#5A4816] text-[#D4AF37] text-xs font-bold">{status==='Avaliacao'?'Challenge':status==='Financiada'?'Funded Pro':status}</span>}
function TradeHistory({trades}:{trades:Trade[]}){const {deleteTrade}=useApp();const sorted=[...trades].sort((a,b)=>b.timestamp-a.timestamp);return <section><div className="flex items-end justify-between mb-3"><div><h3 className="text-lg font-bold">Histórico de Trades</h3><p className="text-xs text-gray-500">{trades.length} registros desta conta</p></div></div>{sorted.length===0?<div className="rounded-2xl border border-dashed border-[#303039] p-8 text-center text-gray-600">Nenhum trade registrado.</div>:<div className="space-y-2">{sorted.map(t=><div key={t.id} className="rounded-2xl border border-[#27272F] bg-[#121217] p-4 flex flex-col md:flex-row md:items-center gap-3"><div className="flex-1"><div className="flex items-center gap-2"><span className="text-sm font-bold">{t.asset}</span><span className="text-[10px] px-2 py-1 rounded-md bg-[#1D1D24] text-gray-400">{t.result}</span><span className="text-[10px] text-gray-600">{t.timeframe}</span></div><p className="text-xs text-gray-500 mt-1">{t.context} · {formatDateTime(t.timestamp)}</p></div><div className={`text-lg font-black ${t.amount>=0?'text-emerald-400':'text-red-400'}`}>{formatSignedCurrency(t.amount)}</div><button onClick={()=>deleteTrade(t.id)} className="text-xs text-gray-600 hover:text-red-400">Excluir</button></div>)}</div>}</section>}
