import { useMemo, useState } from 'react';
import { Award, CalendarDays, Check, ChevronLeft, ChevronRight, Crown, Flag, Lock, MapPin, Target, Briefcase, Plus, DollarSign, Trophy, Rocket, BarChart3 } from 'lucide-react';
import { useApp } from '@/store';

const TRADE_MILESTONES = [25, 50, 100, 250, 500, 1000];
const APP_DAY_MILESTONES = [30, 90, 180, 365];
const TEN_K_MILESTONES = [1, 2, 3, 4];
const SCALE_MILESTONES = [25, 50, 100, 200, 300, 400];
const PAYOUT_MILESTONES = [10000, 25000, 50000, 100000];
const JOURNEY_START_KEY = 'propcontrol_journey_started_at';

function getJourneyStart() { return typeof window === 'undefined' ? null : window.localStorage.getItem(JOURNEY_START_KEY); }

function FamilySilhouette() {
  return <div className="absolute left-1/2 top-[43%] z-10 -translate-x-1/2 -translate-y-1/2 pointer-events-none opacity-90 drop-shadow-[0_0_16px_rgba(255,210,75,.55)]" aria-label="Família" role="img"><svg width="108" height="78" viewBox="0 0 108 78" fill="none"><g fill="#FFE06A"><circle cx="30" cy="14" r="8"/><circle cx="76" cy="14" r="8"/><circle cx="53" cy="21" r="6"/><circle cx="42" cy="29" r="4.5"/><circle cx="64" cy="29" r="4.5"/><path d="M16 66c0-17 6-29 14-29s14 12 14 29H16Z"/><path d="M62 66c0-17 6-29 14-29s14 12 14 29H62Z"/><path d="M39 66c0-13 5-22 14-22s14 9 14 22H39Z"/><path d="M31 66c0-8 4-14 9-14s9 6 9 14H31Z"/><path d="M59 66c0-8 4-14 9-14s9 6 9 14H59Z"/></g></svg></div>;
}

function Progress({ title, current, target, tone = 'gold' }: { title: string; current: number; target: number; tone?: 'gold' | 'green' | 'blue' | 'purple' }) {
  const p = Math.min(100, target ? (current / target) * 100 : 0);
  const bar = tone === 'green' ? 'from-emerald-700 to-emerald-400' : tone === 'blue' ? 'from-blue-800 to-blue-400' : tone === 'purple' ? 'from-purple-800 to-purple-400' : 'from-[#9c6f12] to-[#FFD85A]';
  return <div className="rounded-2xl border border-[#2a2a2e] bg-[#09090a] p-5 shadow-[0_10px_30px_rgba(0,0,0,.2)]"><div className="flex items-end justify-between gap-3"><span className="text-sm text-gray-300">{title}</span><span className="text-xl font-semibold text-white">{current} <span className="text-sm text-gray-500">/ {target}</span></span></div><div className="mt-3 h-2 rounded-full bg-[#252529] overflow-hidden"><div className={`h-full rounded-full bg-gradient-to-r ${bar} transition-all duration-500`} style={{ width: `${p}%` }} /></div><p className="mt-2 text-right text-[11px] text-gray-500">{Math.round(p)}% concluído</p></div>;
}

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section><h2 className="mb-3 text-base font-semibold text-white">{title}</h2><div className="overflow-hidden rounded-2xl border border-[#29292d] bg-[#09090a] divide-y divide-[#202024]">{children}</div></section>; }
function Achievement({ label, done, detail }: { label: string; done: boolean; detail: string }) { return <div className="flex items-center gap-3 px-4 py-3.5"><div className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full border ${done ? 'border-emerald-500/60 bg-emerald-500/15 text-emerald-400' : 'border-[#3a3a3e] bg-[#111113] text-gray-600'}`}>{done ? <Check size={15} /> : <Lock size={14} />}</div><div className="min-w-0 flex-1"><p className="text-sm font-medium text-gray-100">{label}</p><p className="text-[11px] text-gray-500">{detail}</p></div>{done && <span className="text-[11px] font-medium text-emerald-400">Conquistado</span>}</div>; }

export function Journey() {
  const { accounts, trades, movements } = useApp();
  const [chapter, setChapter] = useState<string | null>(null);
  const [journeyStartedAt, setJourneyStartedAt] = useState<string | null>(() => getJourneyStart());
  const startJourney = () => { if (journeyStartedAt) return; const now = new Date().toISOString(); window.localStorage.setItem(JOURNEY_START_KEY, now); setJourneyStartedAt(now); };
  const metrics = useMemo(() => {
    const startMs = journeyStartedAt ? Date.parse(journeyStartedAt) : null;
    const journeyTrades = startMs ? trades.filter(t => t.timestamp >= startMs) : [];
    const journeyMovements = startMs ? movements.filter(m => m.timestamp >= startMs) : [];
    const totalTrades = journeyTrades.length;
    const daysUsingJourney = startMs ? Math.max(1, Math.floor((Date.now() - startMs) / 86400000) + 1) : 0;
    const funded = accounts.filter(a => a.status === 'Financiada');
    const totalPayouts = journeyMovements.filter(m => ['saque', 'payout', 'withdrawal'].includes(String(m.type ?? '').toLowerCase())).reduce((s, m) => s + Number(m.amount || 0), 0);
    return { totalTrades, daysUsingJourney, funded, totalPayouts };
  }, [accounts, trades, movements, journeyStartedAt]);

  const tenKCount = metrics.funded.filter(a => a.size === '10K').length;
  const scaleCurrent = Math.min(metrics.funded.reduce((s, a) => s + (a.size === '100K' ? 100 : Number(a.size.replace('K', ''))), 0), 400);
  const scaleLabels = ['25K', '50K', '100K', '2 × 100K', '3 × 100K', '4 × 100K'];
  const achievementsTotal = TRADE_MILESTONES.length + APP_DAY_MILESTONES.length + TEN_K_MILESTONES.length + SCALE_MILESTONES.length + PAYOUT_MILESTONES.length;
  const achievementsUnlocked = TRADE_MILESTONES.filter(t => metrics.totalTrades >= t).length + APP_DAY_MILESTONES.filter(t => metrics.daysUsingJourney >= t).length + TEN_K_MILESTONES.filter(t => tenKCount >= t).length + SCALE_MILESTONES.filter(t => scaleCurrent >= t).length + PAYOUT_MILESTONES.filter(t => metrics.totalPayouts >= t).length;

  if (chapter) {
    const title = chapter === 'disciplina' ? 'Disciplina' : chapter === 'conquista' ? 'Conquista' : chapter === 'objetivo' ? 'Meu Objetivo' : 'Liberdade';
    const subtitle = chapter === 'disciplina' ? 'Construa o hábito. Permaneça no caminho.' : chapter === 'conquista' ? 'Escale seu capital nas mesas.' : chapter === 'objetivo' ? 'Defina seu sonho e acompanhe seu progresso.' : 'Transforme sua jornada em liberdade financeira.';
    const accent = chapter === 'disciplina' ? 'text-emerald-400 border-emerald-500/40 bg-emerald-500/10' : chapter === 'conquista' ? 'text-blue-400 border-blue-500/40 bg-blue-500/10' : chapter === 'objetivo' ? 'text-purple-400 border-purple-500/40 bg-purple-500/10' : 'text-amber-400 border-amber-500/40 bg-amber-500/10';
    const Icon = chapter === 'disciplina' ? Target : chapter === 'conquista' ? Trophy : chapter === 'objetivo' ? Target : BarChart3;
    return <div className="min-h-screen bg-[#030304] px-3 pb-28 text-white md:px-6"><div className="mx-auto max-w-[720px] pt-4 md:pt-7"><button onClick={() => setChapter(null)} className="mb-5 flex items-center gap-2 text-sm text-gray-400 transition hover:text-white"><ChevronLeft size={18}/> Jornada</button><header className="mb-7 flex items-center justify-between"><div><h1 className="text-[27px] font-bold tracking-tight">{title}</h1><p className="mt-1 text-xs text-gray-400">{subtitle}</p></div><div className={`flex h-16 w-16 items-center justify-center rounded-full border ${accent}`}><Icon size={29}/></div></header>
      {chapter === 'disciplina' && <div className="space-y-7"><Progress title="Trades registrados" current={metrics.totalTrades} target={100} tone="green"/><Section title="Conquistas de trades">{TRADE_MILESTONES.map(t => <Achievement key={t} label={`${t.toLocaleString('pt-BR')} trades registrados`} done={metrics.totalTrades >= t} detail={metrics.totalTrades >= t ? 'Conquistado nesta Jornada' : `Faltam ${t - metrics.totalTrades}`}/>)}</Section><Section title="Conquistas de tempo">{APP_DAY_MILESTONES.map(t => <Achievement key={t} label={`${t} dias de jornada`} done={metrics.daysUsingJourney >= t} detail={metrics.daysUsingJourney >= t ? 'Conquistado' : `Faltam ${t - metrics.daysUsingJourney} dias`}/>)}</Section><div className="rounded-2xl border border-[#29292d] bg-[#0a0a0b] p-4 text-xs text-gray-400"><Award className="mb-2 text-emerald-400" size={20}/>A disciplina não é sobre perfeição. É sobre continuar, mesmo nos dias difíceis.</div></div>}
      {chapter === 'conquista' && <div className="space-y-7"><div className="rounded-2xl border border-blue-500/25 bg-[#090d14] p-5"><p className="text-xs text-gray-400">Capital financiado atual</p><p className="mt-1 text-3xl font-bold">US$ {(scaleCurrent * 1000).toLocaleString('en-US')}</p><p className="mt-3 text-sm text-blue-400">Objetivo: US$ 400.000</p></div><Section title="Contas de 10K">{TEN_K_MILESTONES.map(t => <Achievement key={t} label={`${t} × 10K financiadas`} done={tenKCount >= t} detail={tenKCount >= t ? 'Conquistada' : `Faltam ${t - tenKCount} conta${t - tenKCount === 1 ? '' : 's'}`}/>)}</Section><Section title="Escada de escala">{SCALE_MILESTONES.map((t, i) => <Achievement key={t} label={`${scaleLabels[i]} financiada${i > 2 ? 's' : ''}`} done={scaleCurrent >= t} detail={scaleCurrent >= t ? 'Conquistada' : 'Bloqueada'}/>)}</Section><div className="rounded-2xl border border-[#8b6a1b]/50 bg-[#0d0b06] p-6 text-center"><Crown className="mx-auto text-[#FFD85A]" size={30}/><p className="mt-3 text-sm text-[#D8B75A]">Seu objetivo final</p><p className="mt-1 text-xl font-bold text-[#FFD85A]">4 × 100K FINANCIADAS</p><p className="mt-3 text-sm text-gray-300">US$ 400.000 em capital financiado</p><p className="mt-5 text-xs text-gray-500">Estruture, escale e conquiste sua liberdade.</p></div></div>}
      {chapter === 'objetivo' && <div className="space-y-5"><div className="rounded-2xl border border-purple-500/25 bg-[#0d0913] p-6 text-center"><Target className="mx-auto text-purple-400" size={36}/><h2 className="mt-3 text-xl font-semibold">Qual é o seu próximo sonho?</h2><p className="mt-2 text-sm text-gray-400">Defina um objetivo que faça essa jornada valer a pena.</p><button className="mt-5 w-full rounded-xl bg-purple-500 px-5 py-3 font-semibold text-white"><Plus size={17} className="mr-2 inline"/>Criar meu objetivo</button></div></div>}
      {chapter === 'liberdade' && <div className="space-y-7"><div className="rounded-2xl border border-amber-500/25 bg-[#110e06] p-6"><p className="text-xs text-gray-400">Total recebido em payouts</p><p className="mt-1 text-3xl font-bold">US$ {metrics.totalPayouts.toLocaleString('en-US')}</p><div className="mt-5 h-2 overflow-hidden rounded-full bg-[#29261d]"><div className="h-full rounded-full bg-gradient-to-r from-[#9c6f12] to-[#FFD85A]" style={{ width: `${Math.min(100, metrics.totalPayouts / 100000 * 100)}%` }}/></div><p className="mt-2 text-xs text-gray-500">Próxima conquista: US$ {(PAYOUT_MILESTONES.find(t => metrics.totalPayouts < t) ?? 100000).toLocaleString('en-US')}</p></div><Section title="Suas conquistas financeiras">{PAYOUT_MILESTONES.map(t => <Achievement key={t} label={`US$ ${t.toLocaleString('en-US')}`} done={metrics.totalPayouts >= t} detail={metrics.totalPayouts >= t ? 'Conquistado' : `Faltam US$ ${(t - metrics.totalPayouts).toLocaleString('en-US')}`}/>)}</Section><div className="rounded-2xl border border-[#5d4818] bg-[#0b0a07] p-4 text-xs text-gray-400"><DollarSign className="mb-2 text-[#FFD85A]" size={20}/>Liberdade financeira é resultado de consistência e direção.</div></div>}
    </div></div>;
  }

  const cards = [
    { id: 'disciplina', n: '01', title: 'DISCIPLINA', desc: 'Construa o hábito e permaneça no caminho.', progress: `${metrics.totalTrades} / 100 trades`, Icon: Target, cls: 'border-emerald-500/20 bg-[#080c09] text-emerald-400' },
    { id: 'conquista', n: '02', title: 'CONQUISTA', desc: 'Escale seu capital nas mesas.', progress: `${Math.min(6, SCALE_MILESTONES.filter(t => scaleCurrent >= t).length)} / 6 etapas`, Icon: Trophy, cls: 'border-blue-500/20 bg-[#080b11] text-blue-400' },
    { id: 'objetivo', n: '03', title: 'MEU OBJETIVO', desc: 'Defina seu sonho e acompanhe seu progresso.', progress: 'Personalizado', Icon: Target, cls: 'border-purple-500/20 bg-[#0d0911] text-purple-400' },
    { id: 'liberdade', n: '04', title: 'LIBERDADE', desc: 'Transforme sua jornada em liberdade financeira.', progress: `US$ ${metrics.totalPayouts.toLocaleString('en-US')}`, Icon: BarChart3, cls: 'border-amber-500/20 bg-[#100d07] text-amber-400' }
  ];

  return <div className="min-h-screen bg-[#030304] px-3 pb-28 text-white md:px-6"><div className="mx-auto max-w-[720px] space-y-4 pt-3 md:pt-6">
    <section className="relative min-h-[385px] overflow-hidden rounded-[25px] border border-[#4e3b18] bg-[#050504] shadow-[0_20px_60px_rgba(0,0,0,.45)]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_57%,rgba(255,190,40,.42),transparent_15%),radial-gradient(circle_at_30%_28%,rgba(145,92,31,.24),transparent_27%),radial-gradient(circle_at_75%_25%,rgba(72,51,29,.28),transparent_25%),linear-gradient(180deg,#11100d_0%,#17120b_45%,#070605_100%)]"/><div className="absolute inset-x-0 top-0 h-1/2 bg-[linear-gradient(120deg,transparent_15%,rgba(255,221,155,.09)_40%,transparent_65%)]"/><div className="absolute left-1/2 top-[48%] h-16 w-16 -translate-x-1/2 rounded-full bg-[#FFD85A]/70 blur-[2px] shadow-[0_0_70px_35px_rgba(255,190,45,.22)]"/><FamilySilhouette/><div className="relative z-20 px-5 pt-5 text-center"><div className="flex items-center justify-center gap-2"><Crown size={20} className="text-[#D4AF37]"/><h1 className="text-[26px] font-bold tracking-tight">Jornada</h1></div><p className="mt-1 text-sm text-gray-300">Sua evolução, seu legado.</p></div><div className="relative z-20 mt-[150px] px-5"><div className="flex items-end justify-between"><div><MapPin size={30} className="text-[#FFD85A]"/><p className="mt-1 text-xs font-semibold text-[#FFD85A]">Hoje</p></div><div className="text-right"><Flag className="ml-auto text-[#FFD85A]" size={30}/><p className="mt-1 text-xs font-semibold text-[#FFD85A]">Liberdade</p></div></div><p className="mt-3 text-center text-sm leading-5 text-gray-200">Você está construindo um futuro,<br/>uma <span className="font-semibold text-[#FFD85A]">decisão disciplinada</span> de cada vez.</p></div></section>
    <section className="overflow-hidden rounded-[21px] border border-[#29292d] bg-[#09090a] shadow-[0_10px_30px_rgba(0,0,0,.2)]"><div className="grid grid-cols-3 divide-x divide-[#29292d]"><Stat icon={CalendarDays} label="Dias" value={journeyStartedAt ? String(metrics.daysUsingJourney) : '—'} sub="da Jornada"/><Stat icon={Trophy} label="Conquistas" value={String(achievementsUnlocked)} sub={`/ ${achievementsTotal}`} center/><Stat icon={Rocket} label="Jornada" value={journeyStartedAt ? new Date(journeyStartedAt).toLocaleDateString('pt-BR') : 'Não iniciada'} sub={journeyStartedAt ? 'iniciada em' : 'Comece quando estiver pronto'} /></div></section>
    <section><div className="mb-3 flex items-center justify-between"><h2 className="text-base font-semibold">Seus capítulos</h2><span className="h-0.5 w-8 rounded-full bg-[#D4AF37]"/></div><div className="grid grid-cols-2 gap-3">{cards.map(c => <button key={c.id} onClick={() => setChapter(c.id)} className={`group rounded-[19px] border p-4 text-left transition duration-200 hover:-translate-y-0.5 hover:brightness-110 ${c.cls}`}><div className="flex items-start justify-between"><span className="rounded-full bg-black/30 px-2 py-1 text-xs font-bold">{c.n}</span><c.Icon size={27}/></div><h3 className="mt-4 text-base font-bold">{c.title}</h3><p className="mt-1 min-h-8 text-[11px] leading-4 text-gray-400">{c.desc}</p><div className="mt-4 flex items-center justify-between"><span className="text-[11px] font-semibold">{c.progress}</span><ChevronRight size={16} className="text-gray-500 transition group-hover:translate-x-1"/></div></button>)}</div></section>
    {!journeyStartedAt && <button onClick={startJourney} className="flex w-full items-center justify-center gap-3 rounded-[19px] border border-[#9d7417] bg-gradient-to-r from-[#9e7418] via-[#D4A72C] to-[#B98416] px-5 py-4 text-center font-bold text-black shadow-[0_10px_30px_rgba(180,130,25,.18)] transition hover:brightness-110"><Rocket size={21}/><span>Começar minha Jornada</span></button>}
  </div></div>;
}

function Stat({ icon: Icon, label, value, sub, center = false }: { icon: typeof CalendarDays; label: string; value: string; sub: string; center?: boolean }) { return <div className={`min-w-0 px-3 py-4 ${center ? 'text-center' : ''}`}><div className={`flex items-center gap-2 ${center ? 'justify-center' : ''}`}><Icon size={17} className="shrink-0 text-[#D4AF37]"/><span className="text-[10px] text-gray-500">{label}</span></div><p className="mt-1 truncate text-lg font-semibold text-white">{value}</p><p className="truncate text-[9px] text-gray-500">{sub}</p></div>; }
