import { useEffect, useMemo, useState } from 'react';
import { Modal } from './Modal';
import { SIZE_COLORS, SIZE_VALUES, type AccountSize } from '../types';
import { useApp } from '../store';
import { hydrateRules } from '../propConfig';

export function NewAccountModal({open,onClose}:{open:boolean;onClose:()=>void}){
 const{addAccount,propFirms}=useApp();const[firmId,setFirmId]=useState('');const[programId,setProgramId]=useState('');const[size,setSize]=useState<AccountSize>('25K');const[name,setName]=useState('');const[code,setCode]=useState('');
 const firm=propFirms.find(f=>f.id===firmId)||propFirms[0];const programs=firm?.programs||[];const program=programs.find(p=>p.id===programId)||programs[0];const availableSizes=(program?.sizes||[]).filter(Boolean);const selectedSize=availableSizes.includes(size)?size:(availableSizes[0]||'25K');
 useEffect(()=>{if(open){setName('');setCode('');setFirmId(propFirms[0]?.id||'');setProgramId('');setSize('25K')}},[open,propFirms]);
 useEffect(()=>{if(program&&!program.sizes.includes(size))setSize(program.sizes[0]||'25K')},[program,size]);
 const snapshot=useMemo(()=>program?.phases.map(p=>hydrateRules(p.rules,selectedSize))||[],[program,selectedSize]);
 const save=()=>{if(!name.trim()||!code.trim()||!firm||!program)return;addAccount({name:name.trim(),code:code.trim(),size:selectedSize,propProgramId:program.id,propFirmName:firm.name,propProgramName:program.name,rulesSnapshot:snapshot});onClose()};
 const colors=SIZE_COLORS[selectedSize];
 return <Modal open={open} onClose={onClose} title="Nova Conta"><div className="space-y-5">
  <div><label className="mb-2 block text-xs font-semibold uppercase tracking-wider text-gray-500">Mesa proprietária</label><select className="input" value={firm?.id||''} onChange={e=>{setFirmId(e.target.value);setProgramId('')}}>{propFirms.map(f=><option key={f.id} value={f.id}>{f.name}{f.isOfficial?' · Oficial':''}</option>)}</select></div>
  <div><label className="mb-2 block text-xs font-semibold uppercase tracking-wider text-gray-500">Programa</label><select className="input" value={program?.id||''} onChange={e=>setProgramId(e.target.value)}>{programs.map(p=><option key={p.id} value={p.id}>{p.name} · {p.phases.length} {p.phases.length===1?'fase':'fases'}</option>)}</select></div>
  <div><label className="mb-2 block text-xs font-semibold uppercase tracking-wider text-gray-500">Tamanho da conta</label><div className="grid grid-cols-2 gap-3">{availableSizes.map(s=>{const c=SIZE_COLORS[s];const active=selectedSize===s;return <button key={s} type="button" onClick={()=>setSize(s)} className={`relative rounded-2xl border p-4 text-left transition ${active?`${c.soft} ${c.ring} ring-2 border-transparent`:'border-white/[0.07] bg-[#111214]'}`}><span className={`block text-lg font-black ${active?c.text:'text-gray-300'}`}>{s}</span><span className="mt-1 block text-[11px] text-gray-500">${SIZE_VALUES[s].toLocaleString('en-US')}</span>{active&&<span className={`absolute right-3 top-3 h-2.5 w-2.5 rounded-full ${c.dot}`}/>}</button>})}</div></div>
  <div><label className="mb-2 block text-xs font-semibold uppercase tracking-wider text-gray-500">Nome operacional</label><input value={name} onChange={e=>setName(e.target.value)} placeholder={`Ex: ${firm?.name||'Mesa'} ${selectedSize} #01`} className="input"/></div>
  <div><label className="mb-2 block text-xs font-semibold uppercase tracking-wider text-gray-500">Código Oficial (ID da Conta)</label><input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} inputMode="numeric" placeholder="Ex: 749302" className="input"/></div>
  <div className={`rounded-2xl border ${colors.ring.replace('ring-','border-')}/20 ${colors.soft} p-4`}><div className="flex items-center justify-between"><div><p className={`text-xs font-bold ${colors.text}`}>{firm?.name||'Mesa'} · {program?.name||'Programa'}</p><p className="mt-1 text-[11px] text-gray-500">{program?.phases.length||0} {program?.phases.length===1?'fase':'fases'} · regras vinculadas automaticamente</p></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${colors.soft} ${colors.text}`}>{colors.label}</span></div><div className="mt-4 grid grid-cols-3 gap-2 text-[10px]">{snapshot[0]&&<><div><span className="text-gray-600">Meta</span><strong className="mt-1 block text-gray-300">{snapshot[0].targetPct!=null?`${snapshot[0].targetPct}%`:'—'}</strong></div><div><span className="text-gray-600">Drawdown</span><strong className="mt-1 block text-gray-300">{snapshot[0].maxDrawdown!=null?`$${snapshot[0].maxDrawdown.toLocaleString('en-US')}`:snapshot[0].drawdownType||'—'}</strong></div><div><span className="text-gray-600">Fase</span><strong className="mt-1 block text-gray-300">1 / {program?.phases.length||1}</strong></div></>}</div></div>
  <button onClick={save} disabled={!name.trim()||!code.trim()||!firm||!program} className="w-full rounded-2xl border border-[#D4AF37]/50 bg-[#D4AF37]/[0.06] py-3.5 font-bold text-[#D4AF37] disabled:cursor-not-allowed disabled:opacity-40">Cadastrar Conta</button>
 </div></Modal>;
}
